### ISSUE TITLE
Pass the $event.target instead of $event

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-devdynasty#16]
https://github.com/PUP-BSIT/project-devdynasty/blob/4b16a78089bae788e7fbfca466f7c0211ffa6528/src/app/dashboard/job-list/job-list.component.html#L16
If you just want to add class to this button, you can simply use a template reference variable:
`<button #applyNowButton (click)="applyNowButton.classList.add('clicked')">APPLY NOW!</button>`
I know you will have other implementation in the onApplyClick() so don't apply it. I just want you to know some techniques.

A better approach is, you can directly pass the $event.target
`<button (click)="onApplyClick($event.target)">APPLY NOW!</button`

Then you can update your onApplyClick below and add a TODO with assignment. This way, your code is shorter and cleaner.
https://github.com/PUP-BSIT/project-devdynasty/blob/4b16a78089bae788e7fbfca466f7c0211ffa6528/src/app/dashboard/job-list/job-list.component.ts#L56-L59
```
  onApplyClick(button: HTMLButtonElement) {
    button.classList.add('clicked');
    // TODO(lastName_givenName): Call service/add implementation.
  }
```

Also, add a space after this line:
https://github.com/PUP-BSIT/project-devdynasty/blob/4b16a78089bae788e7fbfca466f7c0211ffa6528/src/app/dashboard/job-list/job-list.component.ts#L55

**Comment by ssvillarosa** [comment]
Team! This ticket is now on its second week. This is not a blockbuster movie. I still don't receive any response/acknowledgement form your end. Do you need a reminder on how to communicate properly?

**Comment by Lopez-JhonLay** [comment]
Good evening sir, sorry for late response. We acknowledged your suggestions to our code, thanks for giving us a better approach to make our code shorter and cleaner.

**Comment by CalderonPearl** [comment]
Good evening, Sir Steven. For follow up, we already applied these approach and suggestions in our project. In this case, we're going to close this issue. We appreciate this great help. Thank you!
