### ISSUE TITLE
No progress update and retrospective for sprint 1

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-devdynasty#5]
https://docs.google.com/presentation/d/1xG5x-A4_CalyCDfSTWFWn44P_wrC9zzNHxJnE1PwG84/edit?usp=sharing
0.1 demerit point for each member.

**Comment by Lopez-JhonLay** [comment]
Good day sir. I am writing on behalf of our group regarding the progress update for our project.We thought that the start of Sprint 1 was scheduled for this week based on your presentation. We have made a progress and are prepared to provide a detailed update.We apologize if there has been any misunderstanding regarding the start date. Could you please confirm the correct timeline for Sprint 1?

**Comment by CalderonPearl** [comment]
Good evening, Sir Steven. We acknowledge that you've announced to our Viber group chat the answer to my team mate's concern. We apologize for the overlook and we will be more wary with our timeline. As we now proceed with our sprints, we will close this issue and mark it resolved. Thank you for your utmost understanding.
